version: "3.7"

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: >
      sh -c "python3 ./manage.py makemigrations accounts &&
             python3 ./manage.py migrate
             gunicorn config.wsgi:application -b 0.0.0.0:3000"
    env_file:
      - ./.env