# Generated by Django 4.1 on 2024-07-13 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_points_user_teams_teams_scancount'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teams',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='team_users_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
