# Generated by Django 4.1 on 2024-07-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teams_user_alter_teams_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='key',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
